spring:
    application:
        name: spring-aperture-simple-api
    data:
        mongodb:
            uri: mongodb://localhost:27017/apiApertureDB
            host: localhost
            port: 27017
            database: apiApertureDB
server:
    port: 8080

mongeez:
  enabled: false

